trailing_whitespace:
  ignores_empty_lines: true
  
line_length:
  ignores_interpolated_strings: true
  ignores_urls: true
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
